# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_harvesters.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15grpc_harvesters.proto\"\"\n\x0e\x41\x63quireRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x41\x63quireReply\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\nHarvesters\x12+\n\x07\x41\x63quire\x12\x0f.AcquireRequest\x1a\r.AcquireReply\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3')



_ACQUIREREQUEST = DESCRIPTOR.message_types_by_name['AcquireRequest']
_ACQUIREREPLY = DESCRIPTOR.message_types_by_name['AcquireReply']
AcquireRequest = _reflection.GeneratedProtocolMessageType('AcquireRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACQUIREREQUEST,
  '__module__' : 'grpc_harvesters_pb2'
  # @@protoc_insertion_point(class_scope:AcquireRequest)
  })
_sym_db.RegisterMessage(AcquireRequest)

AcquireReply = _reflection.GeneratedProtocolMessageType('AcquireReply', (_message.Message,), {
  'DESCRIPTOR' : _ACQUIREREPLY,
  '__module__' : 'grpc_harvesters_pb2'
  # @@protoc_insertion_point(class_scope:AcquireReply)
  })
_sym_db.RegisterMessage(AcquireReply)

_HARVESTERS = DESCRIPTOR.services_by_name['Harvesters']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\003HLW'
  _ACQUIREREQUEST._serialized_start=25
  _ACQUIREREQUEST._serialized_end=59
  _ACQUIREREPLY._serialized_start=61
  _ACQUIREREPLY._serialized_end=92
  _HARVESTERS._serialized_start=94
  _HARVESTERS._serialized_end=151
# @@protoc_insertion_point(module_scope)
