# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_harvesters_pb2 as grpc__harvesters__pb2


class HarvestersStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Acquire = channel.unary_unary(
                '/Harvesters/Acquire',
                request_serializer=grpc__harvesters__pb2.AcquireRequest.SerializeToString,
                response_deserializer=grpc__harvesters__pb2.AcquireReply.FromString,
                )


class HarvestersServicer(object):
    """The greeting service definition.
    """

    def Acquire(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarvestersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=grpc__harvesters__pb2.AcquireRequest.FromString,
                    response_serializer=grpc__harvesters__pb2.AcquireReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Harvesters', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Harvesters(object):
    """The greeting service definition.
    """

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Harvesters/Acquire',
            grpc__harvesters__pb2.AcquireRequest.SerializeToString,
            grpc__harvesters__pb2.AcquireReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
